package cl.consalud.domain.common.model;

import java.util.Arrays;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;
import java.util.stream.Collectors;

public enum Pais {

    ANDORRA("AD", "Andorra"),
    EMIRATOS_ARABES_UNIDOS("AE", "Emiratos Árabes Unidos"),
    AFGANISTAN("AF", "Afganistán"),
    ANTIGUA_Y_BARBUDA("AG", "Antigua y Barbuda"),
    ANGUILA("AI", "Anguila"),
    ALBANIA("AL", "Albania"),
    ARMENIA("AM", "Armenia"),
    ANGOLA("AO", "Angola"),
    ANTARTIDA("AQ", "Antártida"),
    ARGENTINA("AR", "Argentina"),
    SAMOA_AMERICANA("AS", "Samoa Americana"),
    AUSTRIA("AT", "Austria"),
    AUSTRALIA("AU", "Australia"),
    ARUBA("AW", "Aruba"),
    ISLAS_ALAND("AX", "Islas Aland"),
    AZERBAIYAN("AZ", "Azerbaiyán"),
    BOSNIA_Y_HERZEGOVINA("BA", "Bosnia y Herzegovina"),
    BARBADOS("BB", "Barbados"),
    BANGLADES("BD", "Bangladés"),
    BELGICA("BE", "Bélgica"),
    BURKINA_FASO("BF", "Burkina Faso"),
    BULGARIA("BG", "Bulgaria"),
    BAREIN("BH", "Baréin"),
    BURUNDI("BI", "Burundi"),
    BENIN("BJ", "Benín"),
    SAN_BARTOLOME("BL", "San Bartolomé"),
    BERMUDAS("BM", "Bermudas"),
    BRUNEI("BN", "Brunéi"),
    BOLIVIA("BO", "Bolivia"),
    CARIBE_NEERLANDES("BQ", "Caribe neerlandés"),
    BRASIL("BR", "Brasil"),
    BAHAMAS("BS", "Bahamas"),
    BUTAN("BT", "Bután"),
    ISLA_BOUVET("BV", "Isla Bouvet"),
    BOTSUANA("BW", "Botsuana"),
    BIELORRUSIA("BY", "Bielorrusia"),
    BELICE("BZ", "Belice"),
    CANADA("CA", "Canadá"),
    ISLAS_COCOS("CC", "Islas Cocos"),
    REPUBLICA_DEMOCRATICA_DEL_CONGO("CD", "República Democrática del Congo"),
    REPUBLICA_CENTROAFRICANA("CF", "República Centroafricana"),
    CONGO("CG", "Congo"),
    SUIZA("CH", "Suiza"),
    COTE_D_IVOIRE("CI", "Côte d’Ivoire"),
    ISLAS_COOK("CK", "Islas Cook"),
    CHILE("CL", "Chile"),
    CAMERUN("CM", "Camerún"),
    CHINA("CN", "China"),
    COLOMBIA("CO", "Colombia"),
    COSTA_RICA("CR", "Costa Rica"),
    CUBA("CU", "Cuba"),
    CABO_VERDE("CV", "Cabo Verde"),
    CURAZAO("CW", "Curazao"),
    ISLA_DE_NAVIDAD("CX", "Isla de Navidad"),
    CHIPRE("CY", "Chipre"),
    CHEQUIA("CZ", "Chequia"),
    ALEMANIA("DE", "Alemania"),
    YIBUTI("DJ", "Yibuti"),
    DINAMARCA("DK", "Dinamarca"),
    DOMINICA("DM", "Dominica"),
    REPUBLICA_DOMINICANA("DO", "República Dominicana"),
    ARGELIA("DZ", "Argelia"),
    ECUADOR("EC", "Ecuador"),
    ESTONIA("EE", "Estonia"),
    EGIPTO("EG", "Egipto"),
    SAHARA_OCCIDENTAL("EH", "Sáhara Occidental"),
    ERITREA("ER", "Eritrea"),
    ESPANA("ES", "España"),
    ETIOPIA("ET", "Etiopía"),
    FINLANDIA("FI", "Finlandia"),
    FIYI("FJ", "Fiyi"),
    ISLAS_MALVINAS("FK", "Islas Malvinas"),
    MICRONESIA("FM", "Micronesia"),
    ISLAS_FEROE("FO", "Islas Feroe"),
    FRANCIA("FR", "Francia"),
    GABON("GA", "Gabón"),
    REINO_UNIDO("GB", "Reino Unido"),
    GRANADA("GD", "Granada"),
    GEORGIA("GE", "Georgia"),
    GUAYANA_FRANCESA("GF", "Guayana Francesa"),
    GUERNESEY("GG", "Guernesey"),
    GHANA("GH", "Ghana"),
    GIBRALTAR("GI", "Gibraltar"),
    GROENLANDIA("GL", "Groenlandia"),
    GAMBIA("GM", "Gambia"),
    GUINEA("GN", "Guinea"),
    GUADALUPE("GP", "Guadalupe"),
    GUINEA_ECUATORIAL("GQ", "Guinea Ecuatorial"),
    GRECIA("GR", "Grecia"),
    ISLAS_GEORGIA_DEL_SUR_Y_SANDWICH_DEL_SUR("GS", "Islas Georgia del Sur y Sandwich del Sur"),
    GUATEMALA("GT", "Guatemala"),
    GUAM("GU", "Guam"),
    GUINEA_BISAU("GW", "Guinea-Bisáu"),
    GUYANA("GY", "Guyana"),
    RAE_DE_HONG_KONG_CHINA("HK", "RAE de Hong Kong (China)"),
    ISLAS_HEARD_Y_MCDONALD("HM", "Islas Heard y McDonald"),
    HONDURAS("HN", "Honduras"),
    CROACIA("HR", "Croacia"),
    HAITI("HT", "Haití"),
    HUNGRIA("HU", "Hungría"),
    INDONESIA("ID", "Indonesia"),
    IRLANDA("IE", "Irlanda"),
    ISRAEL("IL", "Israel"),
    ISLA_DE_MAN("IM", "Isla de Man"),
    INDIA("IN", "India"),
    TERRITORIO_BRITANICO_DEL_OCEANO_INDICO("IO", "Territorio Británico del Océano Índico"),
    IRAK("IQ", "Irak"),
    IRAN("IR", "Irán"),
    ISLANDIA("IS", "Islandia"),
    ITALIA("IT", "Italia"),
    JERSEY("JE", "Jersey"),
    JAMAICA("JM", "Jamaica"),
    JORDANIA("JO", "Jordania"),
    JAPON("JP", "Japón"),
    KENIA("KE", "Kenia"),
    KIRGUISTAN("KG", "Kirguistán"),
    CAMBOYA("KH", "Camboya"),
    KIRIBATI("KI", "Kiribati"),
    COMORAS("KM", "Comoras"),
    SAN_CRISTOBAL_Y_NIEVES("KN", "San Cristóbal y Nieves"),
    COREA_DEL_NORTE("KP", "Corea del Norte"),
    COREA_DEL_SUR("KR", "Corea del Sur"),
    KUWAIT("KW", "Kuwait"),
    ISLAS_CAIMAN("KY", "Islas Caimán"),
    KAZAJISTAN("KZ", "Kazajistán"),
    LAOS("LA", "Laos"),
    LIBANO("LB", "Líbano"),
    SANTA_LUCIA("LC", "Santa Lucía"),
    LIECHTENSTEIN("LI", "Liechtenstein"),
    SRI_LANKA("LK", "Sri Lanka"),
    LIBERIA("LR", "Liberia"),
    LESOTO("LS", "Lesoto"),
    LITUANIA("LT", "Lituania"),
    LUXEMBURGO("LU", "Luxemburgo"),
    LETONIA("LV", "Letonia"),
    LIBIA("LY", "Libia"),
    MARRUECOS("MA", "Marruecos"),
    MONACO("MC", "Mónaco"),
    MOLDAVIA("MD", "Moldavia"),
    MONTENEGRO("ME", "Montenegro"),
    SAN_MARTIN("MF", "San Martín"),
    MADAGASCAR("MG", "Madagascar"),
    ISLAS_MARSHALL("MH", "Islas Marshall"),
    MACEDONIA_DEL_NORTE("MK", "Macedonia del Norte"),
    MALI("ML", "Mali"),
    MYANMAR_BIRMANIA("MM", "Myanmar (Birmania)"),
    MONGOLIA("MN", "Mongolia"),
    RAE_DE_MACAO_CHINA("MO", "RAE de Macao (China)"),
    ISLAS_MARIANAS_DEL_NORTE("MP", "Islas Marianas del Norte"),
    MARTINICA("MQ", "Martinica"),
    MAURITANIA("MR", "Mauritania"),
    MONTSERRAT("MS", "Montserrat"),
    MALTA("MT", "Malta"),
    MAURICIO("MU", "Mauricio"),
    MALDIVAS("MV", "Maldivas"),
    MALAUI("MW", "Malaui"),
    MEXICO("MX", "México"),
    MALASIA("MY", "Malasia"),
    MOZAMBIQUE("MZ", "Mozambique"),
    NAMIBIA("NA", "Namibia"),
    NUEVA_CALEDONIA("NC", "Nueva Caledonia"),
    NIGER("NE", "Níger"),
    ISLA_NORFOLK("NF", "Isla Norfolk"),
    NIGERIA("NG", "Nigeria"),
    NICARAGUA("NI", "Nicaragua"),
    PAISES_BAJOS("NL", "Países Bajos"),
    NORUEGA("NO", "Noruega"),
    NEPAL("NP", "Nepal"),
    NAURU("NR", "Nauru"),
    NIUE("NU", "Niue"),
    NUEVA_ZELANDA("NZ", "Nueva Zelanda"),
    OMAN("OM", "Omán"),
    PANAMA("PA", "Panamá"),
    PERU("PE", "Perú"),
    POLINESIA_FRANCESA("PF", "Polinesia Francesa"),
    PAPUA_NUEVA_GUINEA("PG", "Papúa Nueva Guinea"),
    FILIPINAS("PH", "Filipinas"),
    PAKISTAN("PK", "Pakistán"),
    POLONIA("PL", "Polonia"),
    SAN_PEDRO_Y_MIQUELON("PM", "San Pedro y Miquelón"),
    ISLAS_PITCAIRN("PN", "Islas Pitcairn"),
    PUERTO_RICO("PR", "Puerto Rico"),
    TERRITORIOS_PALESTINOS("PS", "Territorios Palestinos"),
    PORTUGAL("PT", "Portugal"),
    PALAOS("PW", "Palaos"),
    PARAGUAY("PY", "Paraguay"),
    CATAR("QA", "Catar"),
    REUNION("RE", "Reunión"),
    RUMANIA("RO", "Rumanía"),
    SERBIA("RS", "Serbia"),
    RUSIA("RU", "Rusia"),
    RUANDA("RW", "Ruanda"),
    ARABIA_SAUDI("SA", "Arabia Saudí"),
    ISLAS_SALOMON("SB", "Islas Salomón"),
    SEYCHELLES("SC", "Seychelles"),
    SUDAN("SD", "Sudán"),
    SUECIA("SE", "Suecia"),
    SINGAPUR("SG", "Singapur"),
    SANTA_ELENA("SH", "Santa Elena"),
    ESLOVENIA("SI", "Eslovenia"),
    SVALBARD_Y_JAN_MAYEN("SJ", "Svalbard y Jan Mayen"),
    ESLOVAQUIA("SK", "Eslovaquia"),
    SIERRA_LEONA("SL", "Sierra Leona"),
    SAN_MARINO("SM", "San Marino"),
    SENEGAL("SN", "Senegal"),
    SOMALIA("SO", "Somalia"),
    SURINAM("SR", "Surinam"),
    SUDAN_DEL_SUR("SS", "Sudán del Sur"),
    SANTO_TOME_Y_PRINCIPE("ST", "Santo Tomé y Príncipe"),
    SALVADOR("SV", "El Salvador"),
    SINT_MAARTEN("SX", "Sint Maarten"),
    SIRIA("SY", "Siria"),
    ESUATINI("SZ", "Esuatini"),
    ISLAS_TURCAS_Y_CAICOS("TC", "Islas Turcas y Caicos"),
    CHAD("TD", "Chad"),
    TERRITORIOS_AUSTRALES_FRANCESES("TF", "Territorios Australes Franceses"),
    TOGO("TG", "Togo"),
    TAILANDIA("TH", "Tailandia"),
    TAYIKISTAN("TJ", "Tayikistán"),
    TOKELAU("TK", "Tokelau"),
    TIMOR_LESTE("TL", "Timor-Leste"),
    TURKMENISTAN("TM", "Turkmenistán"),
    TUNEZ("TN", "Túnez"),
    TONGA("TO", "Tonga"),
    TURQUIA("TR", "Turquía"),
    TRINIDAD_Y_TOBAGO("TT", "Trinidad y Tobago"),
    TUVALU("TV", "Tuvalu"),
    TAIWAN("TW", "Taiwán"),
    TANZANIA("TZ", "Tanzania"),
    UCRANIA("UA", "Ucrania"),
    UGANDA("UG", "Uganda"),
    ISLAS_MENORES_ALEJADAS_DE_EE_UU("UM", "Islas menores alejadas de EE. UU."),
    ESTADOS_UNIDOS("US", "Estados Unidos"),
    URUGUAY("UY", "Uruguay"),
    UZBEKISTAN("UZ", "Uzbekistán"),
    CIUDAD_DEL_VATICANO("VA", "Ciudad del Vaticano"),
    SAN_VICENTE_Y_GRANADINAS("VC", "San Vicente y las Granadinas"),
    VENEZUELA("VE", "Venezuela"),
    ISLAS_VIRGENES_BRITANICAS("VG", "Islas Vírgenes Británicas"),
    ISLAS_VIRGENES_DE_EE_UU("VI", "Islas Vírgenes de EE. UU."),
    VIETNAM("VN", "Vietnam"),
    VANUATU("VU", "Vanuatu"),
    WALLIS_Y_FUTUNA("WF", "Wallis y Futuna"),
    SAMOA("WS", "Samoa"),
    YEMEN("YE", "Yemen"),
    MAYOTTE("YT", "Mayotte"),
    SUDAFRICA("ZA", "Sudáfrica"),
    ZAMBIA("ZM", "Zambia"),
    ZIMBABUE("ZW", "Zimbabue");

    private final String code;
    private final String name;
    Pais(String code, String name){
        this.code = code;
        this.name = name;
    }

    /** Código ISO 3166-1 alpha-2 (ej: "CL"). */
    public String getCode() { return code; }

    public String getName() { return name; }

    // Lookup por código (case-insensitive)
    private static final Map<String, Pais> BY_CODE =
            Arrays.stream(values())
                    .collect(Collectors.toUnmodifiableMap(
                            p -> p.code.toUpperCase(Locale.ROOT),
                            Function.identity()));

    public static Optional<Pais> fromCode(String code) {
        if (code == null) return Optional.empty();
        return Optional.ofNullable(BY_CODE.get(code.toUpperCase(Locale.ROOT)));
    }
}